name = "Rsx"
grammar = "rsx"
path_suffixes = ["rsx"]
line_comments = ["// "]
block_comment = ["/* ", " */", "<!-- ", " -->"]
autoclose_before = ":\"'}]>"
brackets = [
    { start = "---", end = "---", close = false, newline = true, not_in = ["comment", "string"] },
    { start = "<script>", end = "</script>", close = false, newline = true, not_in = ["comment", "string"] },
    { start = "<style>", end = "</style>", close = false, newline = true, not_in = ["comment", "string"] },
    { start = "<template>", end = "</template>", close = false, newline = true, not_in = ["comment", "string"] },
    { start = "{{", end = "}}", close = true, newline = false },
    { start = "{{#if", end = "{{/if}}", close = false, newline = true },
    { start = "{{#each", end = "{{/each}}", close = false, newline = true },
    { start = "{{@each", end = "{{/each}}", close = false, newline = true },
    { start = "{{@html", end = "}}", close = false, newline = false },
    { start = "{", end = "}", close = true, newline = true },
    { start = "[", end = "]", close = true, newline = true },
    { start = "(", end = ")", close = true, newline = true },
    { start = "<", end = ">", close = false, newline = false, not_in = ["comment", "string"] },
    { start = "<!--", end = "-->", close = true, newline = false },
    { start = "\"", end = "\"", close = true, newline = false, not_in = ["string"] },
    { start = "'", end = "'", close = true, newline = false, not_in = ["string"] },
    { start = "`", end = "`", close = true, newline = false, not_in = ["string"] },
]

[overrides.string]
line_comments = { remove = true }
block_comment = { remove = true }

[overrides.comment]
line_comments = { remove = true }
block_comment = { remove = true }
